# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: qtasks.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'qtasks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cqtasks.proto\x12\tqtasks.v1\"i\n\x0e\x41\x64\x64TaskRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\t\x12\x13\n\x0bkwargs_json\x18\x03 \x01(\t\x12\x0f\n\x07timeout\x18\x04 \x01(\x01\x12\x10\n\x08priority\x18\x05 \x01(\x05\"O\n\x0f\x41\x64\x64TaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\r\n\x05\x65rror\x18\x04 \x01(\t\"6\n\x0eGetTaskRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\x12\x16\n\x0einclude_result\x18\x02 \x01(\x08\"d\n\x0fGetTaskResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x13\n\x0bresult_json\x18\x03 \x01(\t\x12\x11\n\ttraceback\x18\x04 \x01(\t\x12\r\n\x05\x65rror\x18\x05 \x01(\t2\x93\x01\n\rQTasksService\x12@\n\x07\x41\x64\x64Task\x12\x19.qtasks.v1.AddTaskRequest\x1a\x1a.qtasks.v1.AddTaskResponse\x12@\n\x07GetTask\x12\x19.qtasks.v1.GetTaskRequest\x1a\x1a.qtasks.v1.GetTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'qtasks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDTASKREQUEST']._serialized_start=27
  _globals['_ADDTASKREQUEST']._serialized_end=132
  _globals['_ADDTASKRESPONSE']._serialized_start=134
  _globals['_ADDTASKRESPONSE']._serialized_end=213
  _globals['_GETTASKREQUEST']._serialized_start=215
  _globals['_GETTASKREQUEST']._serialized_end=269
  _globals['_GETTASKRESPONSE']._serialized_start=271
  _globals['_GETTASKRESPONSE']._serialized_end=371
  _globals['_QTASKSSERVICE']._serialized_start=374
  _globals['_QTASKSSERVICE']._serialized_end=521
# @@protoc_insertion_point(module_scope)
