name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11.5'

    - name: Install dependencies
      run: pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-static-i18n

    - name: Deploy to GitHub Pages
      run: PYTHONPATH=src mkdocs gh-deploy --config-file docs/mkdocs.yml --force
